officer_columns = [
    {"officer_first_name": "text"},
    {"officer_middle_name": "text"},
    {"officer_last_name": "text"},
    {"officer_preferred_name": "text"},
    {"officer_birthday": "text"},
    {"officer_gender": "text"},
    {"officer_nationality": "text"},
    {"officer_blood_type": "text"},
    {"officer_employee_id": "text"},
    {"officer_badge_number": "text"},
    {"officer_social_security_number": "text"},
    {"officer_primary_email": "text"},
    {"officer_secondary_email": "text"},
    {"officer_work_phone": "text"},
    {"officer_mobile_phone": "text"},
    {"officer_primary_contact_name": "text"},
    {"officer_primary_contact_phone_number": "text"},
    {"officer_primary_contact_relationship": "text"},
    {"officer_secondary_contact_name": "text"},
    {"officer_secondary_contact_phone_number": "text"},
    {"officer_secondary_contact_relationship": "text"},
    {"officer_employment_job_title": "text"},
    {"officer_employment_department": "text"},
    {"officer_employment_type": "text"},
    {"officer_employment_start_date": "text"},
    {"officer_employment_reporting_officer": "text"},
    {"officer_employment_work_location": "text"},
    {"officer_employment_history": "text"},
    {"officer_document_list": "text"},
    {"officer_pin": "text"},
    {"officer_username": "text"},
    {"officer_is_admin": "text"}
]
task_columns = [
    {"task_title": "text"},
    {"task_description": "text"},
    {"task_priority": "text"},
    {"task_officer_badge_number": "text"}
]
report_columns = [
    {"report_caseNum": "text"},
    {"report_submitting_officer": "text"},
    {"report_submitting_datetime": "text"},
    {"report_location": "text"},
    {"report_type": "text"},
    {"report_status": "text"},
    {"report_video": "text"},
    {"report_reviewing_officer": "text"},
    {"report_reviewing_datetime": "text"},
    {"report_reviewing_reason": "text"},
    {"report_is_read": "text"},
    {"report_officer_badge_number": "text"},
    {"report_real_submission_datetime": "text"}
]